### ISSUE TITLE
10.15.7 直接升级 big sur 正式版，DW1820A蓝牙固件无法加载

### ISSUE THREAD

**Issue by lslzl3000** [daliansky/Lenovo-TianYi-510S-Mini-Hackintosh#10]
直接尝试了系统直接升级，升级时间巨长，然后第一次进入系统，DW1820A的蓝牙和wifi全部失效，再次重启一遍后，wifi正常驱动了，网络没有问题，但蓝牙无法正常工作，可以扫描到周围设备，但无法连接，用hackintool查看，蓝牙的固件没有加载~

请问如何修复呢？应该不是efi本身的问题，是需要重建缓存还是什么操作吗？

**Comment by lslzl3000** [comment]
重复关机开机几次后~ 蓝牙有又神奇的恢复驱动了~  什么原理呢？
目前正常使用蓝牙设备，但仍然无法使用隔空投送~ 求解？

**Comment by boboqun** [comment]
勇士你好，前来观望，为你点赞

**Comment by daliansky** [comment]
关机断电等3分钟后再插电开机治百病
