### ISSUE TITLE
最新1.5.0 efi 无法安装11.2.2更新，boot菜单没有出现更新选项

### ISSUE THREAD

**Issue by lslzl3000** [daliansky/Lenovo-TianYi-510S-Mini-Hackintosh#11]
目前11.2，之前11升11.1/11.2都是正常的，但这次系统内选择更新11.2.2，但重启后boot菜单内没有出现更新选项，无法进入安装步骤
是我的个人问题，还是efi设置问题？目前采用1.5.0 efi

**Comment by daliansky** [comment]
安装更新使用v1.0.0的EFI
日常使用EFI v1.5.0
