### ISSUE TITLE
DW1820A 经常蓝牙失效，必须拔电源后才能恢复，无解吗？

### ISSUE THREAD

**Issue by lslzl3000** [daliansky/Lenovo-TianYi-510S-Mini-Hackintosh#12]
510s更换了小兵之前推荐的 DW1820A，屏蔽了针脚，平时用起来倒是非常OK，但经常出现开机/重启/睡眠后蓝牙连接不上的问题，兵哥博客说偶尔才会出现，但我这里有超过50%的概率，必须关机后拔电源再开机后才能恢复，这个概率太高了，特别影响使用感受，请问有解决方案吗？

**Comment by kezhuoquan** [comment]
我也是1820a有时候蓝牙不能使用，后来换了943602cs就完美了
