### ISSUE TITLE
感谢大佬，期待教程！

### ISSUE THREAD

**Issue by boboqun** [daliansky/Lenovo-TianYi-510S-Mini-Hackintosh#2]
刚收到这个设备，配的是PM991，请问这个固态需要换吗？

**Comment by lslzl3000** [comment]
理论上可以装，但需要通过恢复的方法安装才行，网上很多教程，请自行搜索
不是很推荐这个硬盘，很麻烦，每次升级也得来回折腾，而且据说pm991/981用起来也不稳定，经常出问题，所以最好花几百块钱换个固态吧，也不贵

**Comment by boboqun** [comment]
好嘞，那就换兵哥说的那款西数的。
