### ISSUE TITLE
用刚更新的efi安装卡住

### ISSUE THREAD

**Issue by boboqun** [daliansky/Lenovo-TianYi-510S-Mini-Hackintosh#4]
用刚刚更新的efi安装卡住
硬盘1已换WD SN750
硬盘2未拆
网卡未换
如图卡到了这个位置，很尴尬显示器下边有一部分不显示
![微信图片_20201013175555](https://user-images.githubusercontent.com/20718624/95846066-8ea23400-0d7d-11eb-92c5-f27e8fd2bd60.jpg)
大佬知道怎么解决吗？

**Comment by lslzl3000** [comment]
@daliansky 🙏出一个简单安装教程吧，bios相关设置等，感谢

**Comment by boboqun** [comment]
系统用的是这个【黑果小兵】【微信首发】macOS Big Sur Public Beta 3 20A5364e Installer for OpenCore 0.6.1 and PE双EFI分区原版镜像  https://blog.daliansky.net/WeChat-First-macOS-Big-Sur-Beta-4-20A5343i-Installer-for-OpenCore-0.6.0-and-PE-dual-EFI-partition-original-image.html

**Comment by gsjaylab** [comment]
这个efi天逸510s可以用吗？不带mini的

**Comment by mrlagmr** [comment]
![image](https://user-images.githubusercontent.com/60417146/95947773-e7c3a380-0e21-11eb-8444-7d8c8d22a01a.jpeg)

我用1.0.0版EFI也没有办法正常引导安装，卡在了上图的位置，安装系统用的是小兵的19H2。试着换了iMac 19，1 和 20，1都是一样的状况。

**Comment by boboqun** [comment]
![微信图片_20201014134100](https://user-images.githubusercontent.com/20718624/95948330-f494c700-0e22-11eb-9f2d-379ec5f77b7e.jpg)
嗯，我用19H2和楼上应该是卡到了一样的位置

**Comment by haoxingwang** [comment]
bios显示设置不要选自动，可以安装，但是紫屏
![image](https://user-images.githubusercontent.com/16429312/95988144-08f4b600-0e5b-11eb-8c78-bd072681cd47.jpg)

**Comment by haoxingwang** [comment]
> bios显示设置不要选自动，可以安装，但是紫屏
> ![image](https://user-images.githubusercontent.com/16429312/95988144-08f4b600-0e5b-11eb-8c78-bd072681cd47.jpg)

我的是HDMI

**Comment by mrlagmr** [comment]
> bios显示设置不要选自动，可以安装，但是紫屏
> 
> ![image](https://user-images.githubusercontent.com/16429312/95988144-08f4b600-0e5b-11eb-8c78-bd072681cd47.jpg)
> 
> 

感谢，好像可以安装了，用mDP接口没有怎么出现紫屏的现象，只有一开始Apple logo下面的进度条是紫屏，不过不影响安装。

![image](https://user-images.githubusercontent.com/60417146/95999632-a99da280-0e68-11eb-9937-ca47f00d2fa8.jpeg)

**Comment by haoxingwang** [comment]
> > bios显示设置不要选自动，可以安装，但是紫屏
> > ![image](https://user-images.githubusercontent.com/16429312/95988144-08f4b600-0e5b-11eb-8c78-bd072681cd47.jpg)
> 
> 感谢，好像可以安装了，用mDP接口没有怎么出现紫屏的现象，只有一开始Apple logo下面的进度条是紫屏，不过不影响安装。
> 
> ![image](https://user-images.githubusercontent.com/60417146/95999632-a99da280-0e68-11eb-9937-ca47f00d2fa8.jpeg)

我是HDMI😭

**Comment by boboqun** [comment]
我搞定了，bios里选板载显卡64m，就成功装上了

**Comment by lslzl3000** [comment]
hdmi紫屏，dp口转hdmi黑屏无显示… 有人知道怎么解决吗？
另外，测试intel 驱动还很不完善，用起来很麻烦，即使换成alpha版的airportitlwm，也很不稳定，隔空投送这类的功能也不能用

**Comment by boboqun** [comment]
此 issue 关闭，有关 hdmi 紫屏问题请转到另外的 issue [hdmi紫屏](https://github.com/daliansky/Lenovo-TianYi-510S-Mini-Hackintosh/issues/5)
