### ISSUE TITLE
HDMI紫屏，DP转HDMI黑屏

### ISSUE THREAD

**Issue by lslzl3000** [daliansky/Lenovo-TianYi-510S-Mini-Hackintosh#5]
BIOS里选64mb，其他默认安装倒是无问题，但HDMI显示紫屏，配置里看是30寸的显示器，只有1080分辨率，换DP转HDMI的线又完全黑屏，应该如何修改opencore的配置呢，求前辈指教

**Comment by lslzl3000** [comment]
包括视频播放错误，framebuffer兵哥应该已经针对这款打过补丁呀，为什么会不正常呢？ 显示器有问题？

**Comment by lslzl3000** [comment]
@daliansky 定制的framebuffer难道每个机子还不太一样么？还是说跟显示器也有关系呢？尝试重新生成补丁但没成功

**Comment by lslzl3000** [comment]
经测试，家里2台2k分辨率的屏幕，一个支持dp&hdmi口，一个只有hdmi

1. 直接用dp线连dp口显示器可以正常显示

2. dp转hdmi接口就黑屏，但另一个8代核显clover引导（10.15.7, 没有framebuffer补丁，只有添加-disablegfxfirmware而已）的黑果dp转hdmi接口(同一条线)就正常~~ 说明应该还是兵哥现在对这款机器的framebuffer还是有bug

3. 单独hdmi连接出现紫屏，并且无法识别2k分辨率只有1080p（系统信息显示为30寸电视），同时接dp和hdmi的话，dp正常2k输出，hdmi还是1080紫屏

尝试用hackintool定制framebuffer但不成功，难道是显示器的问题？ 主要是dp转hdmi黑屏需要解决，hdmi紫屏可以不用，希望有人知道解决方案

**Comment by lslzl3000** [comment]
经测试，可能是10代核显在mac上对dp转hdmi对线材有要求，普通改的dp1.2转hdmi无法驱动（8代核显没有限制），需要内含主动式芯片的线材，或者dp1.4转hdmi2.0的线材，我目前测试网上常见的dp转hdmi芯片ps176/177/186等应该都可以，那种便宜的30-50元的ps8xxx的芯片是不行的

**Comment by daliansky** [comment]
1. 截止到目前为止，已经解决了单插`HDMI`安装及使用的问题，但是需要注入`EDID`才行，而`EDID`的注入就比较复杂了；尤其是在安装前需要提取`EDID`信息并注入到`config.plist`里才行；
2. https://github.com/daliansky/Lenovo-TianYi-510S-Mini-Hackintosh/issues/4 的HDMI安装有可能用的是好点的线材，我手上的线材做不到单插紫屏进安装或者使用，如果采用`DP+HDMI`才可以；

**Comment by daliansky** [comment]
配套的EFI已经注入了edid，可以在安装完成后再替换为高版本的efi使用，该问题关闭
