### ISSUE TITLE
dp连接显示器扬声器不可用

### ISSUE THREAD

**Issue by boboqun** [daliansky/Lenovo-TianYi-510S-Mini-Hackintosh#6]
dp连接aoc u2790pqu 4K显示器，声音选项里仅有内建扬声器，实际不可用。3.5毫米耳机孔插入耳机的话有时可播放声音，有时不可以。插入3.5毫米耳机的麦克风不可用，实际使用的是内建麦克风。拔掉3.5毫米耳机后内建麦克风也会不可用。1820A的蓝牙耳机和麦克风一切正常。DW201的蓝牙耳机扬声器正常，麦克风不可用。
蓝牙耳机使用的是sony wi1000xm2，3.5毫米耳机使用的是锤子s-1000耳机

**Comment by boboqun** [comment]
有没有大佬知道dp扬声器的解决方法？

**Comment by lslzl3000** [comment]
我没显示器音响，测试如果开机没插耳机，则后面再插耳机都没用，无法识别耳机插孔设备。如果开机插着耳机，则会一直识别为耳机输出，拔了也不会显示内建音频
兵哥不知道测的是hdmi音频还是dp音频

**Comment by daliansky** [comment]
该问题已经修复，会话关闭
