### ISSUE TITLE
10-26更新EFI引导出错，无法启动

### ISSUE THREAD

**Issue by lslzl3000** [daliansky/Lenovo-TianYi-510S-Mini-Hackintosh#8]
无论是否启用edid注入，10-26日更新的efi引导都出错，无论是否启用edid，开机均无法引导gpu驱动导致kernel panic，有其他人遇到同样问题吗？

**Comment by daliansky** [comment]
无图无真相，检查BIOS是否设置了`DVMT`为`64MB`
