### ISSUE TITLE
最近想入手，请问能告诉我下 黑苹果有哪些缺陷吗

### ISSUE THREAD

**Issue by ZhangJian002** [daliansky/Lenovo-TianYi-510S-Mini-Hackintosh#9]
最近想入手，请问能告诉我下 黑苹果有哪些缺陷吗，还有性能这块能发挥出windows下的几成性能

**Comment by daliansky** [comment]
性能这块你还是网上找评测看下具体的对比数据，我没太关注这一块

**Comment by ZhangJian002** [comment]
> 性能这块你还是网上找评测看下具体的对比数据，我没太关注这一块

那现有缺陷有哪些，可以列举下吗，我看能不能接受

**Comment by lslzl3000** [comment]
@ZhangJian002 不同的机器，不同的优化最终的效果肯定不一样，性能问题我测试跟windows没有差距，macos的优化在许多app上还更好，目前这款机器能做到99%的完美黑苹果，但需要更换原装固态硬盘和无线网卡

目前这款efi没有发现明显缺陷，我是做主力机使用的，所有功能正常，好像只有耳机插孔还不能动态插拔切换，需要使用开机前插入才能识别，不过影响不大，我是一直接插着外置扬声器了，耳机都用蓝牙的。
另外，推荐用DP口的显示器使用，HDMI单独输出有问题， 不过10-26版efi兵哥说修复了（本身edid注入也比较麻烦），不过我测试新版无法引导~ 索性我也不追求了，dp转hdmi就行

**Comment by ZhangJian002** [comment]
感谢老哥~
